# Preface {.unnumbered}

I had my first ride in a kite buggy July 4, 1992. My ride was a Peter Lynn buggy. That was so early in buggy history I don't even think it had a model. Later I bought a Peter Lynn Comp buggy, then another of the same. In maybe 2009, I bought a Peter Lynn XR+ and then a Flexifoil buggy. I never had a great way to carry tools, water, or any other gear. In 2014 I purchased a hydration backpack, but it was too small to carry anything but water. I would tie tools to the buggy frame just so I could tighten a loose bolt if my buggy came undone away from camp. Sometimes I would loose a wrench or a ground stake while riding and never find it again. After each session I had to hose and dry my wrenches to keep the from seizing up with sand and corrosion.

In the Summer of 2021, I finally purchased a decent hydration backpack that could carry my water and just enough gear. It had room for a few wrenches, a multi-tool, a line set, a fid, spar pocket repair supplies, repair tape, my car keys and a phone. The backpack held everything and it could keep everything dry. I finally had a enough tools and parts on me I could break down miles from camp and probably fly home. It was a model from Osprey and I loved it. I used it every time I went buggying and it served very well. I was thrilled to have finally solved my gear management problem.

Yet a year later I upended that happy world when I placed an order for a really nice buggy. I wanted a buggy with a broader wheel base, larger wheel diameter, hip-lock, and better frame geometry. So I ordered a GT-Race R6 from Martin Faber. While I was waiting for Martin to build it, I realized my fancy Osprey backpack would never work on this modern, high-backed buggy. I began searching for a solution and decided the best option was to build a custom backpack tailored to the buggy and to center the design around a really big water bladder.

Version 1 was nothing but a fabric grocery bag tied to behind the buggy seat with a 3 liter Osprey water bladder inside. That was for the shakedown cruise of the new GT buggy in September 2022. Version 2 was a part of seat rebuild when the seat on my daughter's Peter Lynn Comp buggy failed. Version 3, the proper prototype for the GT buggy, is what you see pictured in this book.

I might never have made the book, but mine wasn't the only GT-Race buggy to cross the Atlantic last Fall. Errol Hartbarger got the bug to buy a new GT buggy the same time I did. We ordered them the same week and Martin shipped the pair to the US together a few months later. I promised Errol I'd make him a backpack, too. I wrote 23 pages of notes in designing my backpack, but they were so poorly sequenced and error-filled I wasn't sure I could execute a second one without goofing it up a few times on the way.

This book is my effort to turn those notes and the photographs I took during and after the build into a complete document describing how to build a backpack for a GT-Race R6 buggy like mine. I have included everything I did and learned in constructing the Version 3 backpack. My hope it that Errol's backpack can be a little better design with fewer mistakes in the construction. I hope others find the book useful as well.

*Philip Chase, March 2023*
